//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMixes {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MyMixes.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        internal static string MixLocationsNoPlaylist {
            get {
                return ResourceManager.GetString("MixLocationsNoPlaylist", resourceCulture);
            }
        }
        
        internal static string MixLocationsNoPlaylistTitle {
            get {
                return ResourceManager.GetString("MixLocationsNoPlaylistTitle", resourceCulture);
            }
        }
        
        internal static string NoMixLocations {
            get {
                return ResourceManager.GetString("NoMixLocations", resourceCulture);
            }
        }
        
        internal static string NoMixLocationsTitle {
            get {
                return ResourceManager.GetString("NoMixLocationsTitle", resourceCulture);
            }
        }
        
        internal static string NoPlaylist {
            get {
                return ResourceManager.GetString("NoPlaylist", resourceCulture);
            }
        }
        
        internal static string NoPlaylistTitle {
            get {
                return ResourceManager.GetString("NoPlaylistTitle", resourceCulture);
            }
        }
        
        internal static string NoProjects {
            get {
                return ResourceManager.GetString("NoProjects", resourceCulture);
            }
        }
        
        internal static string NoProjectsTitle {
            get {
                return ResourceManager.GetString("NoProjectsTitle", resourceCulture);
            }
        }
        
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        internal static string RemoveFolder {
            get {
                return ResourceManager.GetString("RemoveFolder", resourceCulture);
            }
        }
        
        internal static string RemoveFolderRemoteFailed {
            get {
                return ResourceManager.GetString("RemoveFolderRemoteFailed", resourceCulture);
            }
        }
        
        internal static string RemoveFolderRemoteFailedTitle {
            get {
                return ResourceManager.GetString("RemoveFolderRemoteFailedTitle", resourceCulture);
            }
        }
        
        internal static string RemoveFolderTitle {
            get {
                return ResourceManager.GetString("RemoveFolderTitle", resourceCulture);
            }
        }
        
        internal static string SongPlayFailed {
            get {
                return ResourceManager.GetString("SongPlayFailed", resourceCulture);
            }
        }
        
        internal static string SongPlayFailedTitle {
            get {
                return ResourceManager.GetString("SongPlayFailedTitle", resourceCulture);
            }
        }
    }
}
